name: Feature request
description: Suggest a new feature for OLS
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: Short feature name
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the feature
    validations:
      required: true
